### ISSUE TITLE
변경이 안됩니다.

### ISSUE THREAD

**Issue by nevercaution** [bluewings/pokemon-go-helper#1]
스크립트를 돌렸는데 이름이 변경이 안되네요. 막혔나요?

**Comment by nevercaution** [comment]
두번 돌리니까 되네요? 시간이 지연이 있는건지요.

**Comment by bluewings** [comment]
@nevercaution 
오랫동안 두었다가 첫 실행할 때 안되는 경우가 있더군요. 저도 가끔씩 두번 돌립니다. ㅠ_ㅠ;
RenamePokemon API 같은 경우는 https://github.com/Armax/Pokemon-GO-node-api 에서도 관리가 안되고 있어서 callback 실행이 안됩니다. 실행 결과를 callback 으로 받을 수 있게 되면 누락된 항목등도 로그에 표시되도록 수정할 예정입니다.

**Comment by bluewings** [comment]
@nevercaution 
포켓몬 고 앱 자체가 짧은 주기로 계속 인벤토리 목록을 갱신하기 때문에 반영은 수십초 이내로 됩니다.
포켓몬 목록 화면 띄워놓으신 상태에서 리프래시나 화면 이동 없이 확인이 가능합니다.
