### ISSUE TITLE
패스워드가 history에 남아서 조금 찜찜한데 prompt로 받게 하면 좋지 않을까요?

### ISSUE THREAD

**Issue by amitabul** [bluewings/pokemon-go-helper#2]
구글 계정은 소중하니까..

너무 좋아요~~~

**Comment by bluewings** [comment]
@amitabul 
진화 및 진화시 신규 포켓몬 점수 계산 스크립트 추가 예정인데, 그때 고민해보겠습니다.
아니면 아래 라인에 입력해두시고 파라미터 없이 ```node index.js``` 만 실행해주세요.
https://github.com/bluewings/pokemon-go-helper/blob/master/index.js#L7-L8
잘 쓰셨으면 우상단에 star 클릭 부탁드려요. ^_^

**Comment by bluewings** [comment]
@amitabul 
수정되었습니다. ```git pull``` 받으신 후에 ```npm install``` 한 번 해주시고
```node.index``` 혹은 ```npm start``` 하시면 아래와 같이 사용하실 수 있습니다.
(파라미터를 넘기는 경우 기존과 동일하게 동작합니다. crontab 을 사용하시는 분들도 계시거든요...)

```
$ npm start

> pokemon-go-helper@1.0.0 start /Users/sungwoncha/misc/pokemon-go-helper
> node index.js

[Pokémon Go Helper] gmail: youraccount@gmail.com
[Pokémon Go Helper] password: ********
[Pokémon Go Helper] location: 
[i] Logging with user: youraccount@gmail.com
[i] Received Google access token!
[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/390/rpc
[i] Current location: 경기도 성남시 분당구 정자동
[i] lat/long/alt: : 37.3638388 127.1163207 0
[i] updateing 3 items.
[i] update nickname: 구구 51 C •
[i] update nickname: 골덕 93 S
[i] update nickname: 가디 71 B
```
