### ISSUE TITLE
API Endpoint가 정상적으로 나오지 않는 것 같습니다.

### ISSUE THREAD

**Issue by makeajourney** [bluewings/pokemon-go-helper#3]
```
[i] Received API Endpoint: https://null/rpc
[i] Current location: 경기도 성남시 분당구 정자동
[i] lat/long/alt: : 37.3638388 127.1163207 0
[i] execute 'rename' task. : 포켓몬의 닉네임을 변경합니다.
(node:15615) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error
(node:15615) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

그저께까지 잘 사용했었는데 오늘 실행해보이 이런 문제가 생겼는데 어떻게 해결 가능할까요?

**Comment by bluewings** [comment]
혹시 지금도 안되나요?
제가 방금 확인해봤을때는 잘 동작하고 있습니다. 
```
[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/168/rpc
[i] Current location: 경기도 성남시 분당구 정자동
[i] lat/long/alt: : 37.3638388 127.1163207 0
```
API Endpoint 를 정상적으로 얻어오고 있습니다.

제가 사용한 [Pokemon-GO-node-api](https://github.com/Armax/Pokemon-GO-node-api)에 올라온 이슈 중에 AWS, Heroku 등 클라우드 서비스에서 돌리는 경우 안된다는 사례가 있고, reddit 을 보면 계정은 아니고 IP 기반 서버 블락에 관한 소문도 있긴합니다.
혹시 배치로 돌리고 계시다면 빈도를 줄여보시고 다른 IP (노트북이시라면 핸드폰 테더링 등을 이용) 에서 한번 시도해보세요.

**Comment by bluewings** [comment]
@makeajourney 
제가 지난 주말부터 어제까지 컴퓨터를 쓸 수 없는 상황이었는데,
지인 분들께 여쭤보니 어제 그저께 로그인 자체가 안되었다는 분들이 계시더군요. 어제 밤부터는 다시 정상적으로 동작하고 있다고 합니다. 지금 다시 확인해보세요.
