### ISSUE TITLE
receive endpoint가 null 로 나옵니다

### ISSUE THREAD

**Issue by sungbine** [bluewings/pokemon-go-helper#4]
[i] Received API Endpoint: https://null/rpc

이렇게 나옵니다

**Comment by sungbine** [comment]
closed된 이슈 확인했습니다.

**Comment by bluewings** [comment]
@sungbine 
과거부터 비슷한 에러가 종종 발생하고 있었나봅니다. 
https://github.com/Armax/Pokemon-GO-node-api/issues/112

오늘 아침엔 되더니 다시 해당 값이 빈채로 넘어오고 있습니다. 현재 계정에 관계없이 아래 값이 비어서 넘어오네요.
잠시 뒤(?)에 다시 해보세요.
https://github.com/Armax/Pokemon-GO-node-api/blob/master/pokemon.proto#L130

**Comment by bluewings** [comment]
@sungbine @makeajourney
기존에 사용하던 라이브러리에서 위 이슈가 주기적으로 발생할 것으로 우려되어 라이브러리의 종류를 변경하였습니다.
[Pokemon-GO-node-api](https://github.com/Armax/Pokemon-GO-node-api) → [pogobuf](https://github.com/cyraxx/pogobuf)
```git pull``` 하신 후에 ```npm install``` 하시고 실행하시면 됩니다.
